name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      # Clonar el repo
      - uses: actions/checkout@v3

      # Subir los archivos directamente sin build
      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RECARGARBATERIASYPAGOS }}
          action: "upload"           # solo subir archivos
          app_location: "/"          # index.html en la raíz
          api_location: ""           # sin backend
          output_location: "/"       # sin carpeta de build
          app_build_command: ""      # DESACTIVAR build de Node.js
